# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{usvn-crowd-sync}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["crazycode"]
  s.date = %q{2011-06-02}
  s.default_executable = %q{usvn-crowd-sync}
  s.description = %q{Sync Atlassian crowd's user & groups to USVN.}
  s.email = %q{crazycode@gmail.com}
  s.executables = ["usvn-crowd-sync"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/usvn-crowd-sync",
    "lib/crowd.rb",
    "lib/crowd/crowd.rb",
    "lib/crowd/crowd.yml",
    "lib/crowd/crowd_authentication.rb",
    "lib/crowd/default.rb",
    "lib/crowd/defaultDriver.rb",
    "lib/crowd/defaultMappingRegistry.rb",
    "lib/crowd/version.rb",
    "lib/usvn-crowd-sync.rb",
    "lib/usvn/usvn_0_x.rb",
    "spec/spec_helper.rb",
    "spec/usvn-crowd-sync_spec.rb",
    "tools/regenerate_authz_file.php",
    "usvn-crowd-sync.yml"
  ]
  s.homepage = %q{http://github.com/crazycode/usvn-crowd-sync}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.6.2}
  s.summary = %q{Sync Atlassian crowd's user & groups to USVN.}
  s.test_files = [
    "spec/spec_helper.rb",
    "spec/usvn-crowd-sync_spec.rb"
  ]

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_runtime_dependency(%q<data_mapper>, [">= 0"])
      s.add_runtime_dependency(%q<dm-mysql-adapter>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
    else
      s.add_dependency(%q<rspec>, ["~> 2.3.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<data_mapper>, [">= 0"])
      s.add_dependency(%q<dm-mysql-adapter>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
    end
  else
    s.add_dependency(%q<rspec>, ["~> 2.3.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<data_mapper>, [">= 0"])
    s.add_dependency(%q<dm-mysql-adapter>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
  end
end

